In [4]:
import pandas as pd

## Завдання 1
У вас є дані про користувачів із полями: "Ім'я", "Вік" і "Місто".
 * Створіть DataFrame зі словника Python із п'ятьма записами.
 * Виведіть весь DataFrame.
 * Визначте кількість рядків і стовпців.
 * Виведіть назви всіх стовпців.
 * Покажіть перші три рядки таблиці.

In [5]:
dict_users = {  # для датасету необхідно щоб масиви всіх полів мали однаковий розмір
    "Ім'я": ["Аскольд", "Олег", "Ігор", "Ольга", "Святослав"],
    "Вік": [30, 33, 42, 27, 37],
    "Місто": ["Київ", "Хотин", "Чернігів", "Вишгород", "Васильків"],
}

users = pd.DataFrame(dict_users)

users

        Ім'я  Вік      Місто
0    Аскольд   30       Київ
1       Олег   33      Хотин
2       Ігор   42   Чернігів
3      Ольга   27   Вишгород
4  Святослав   37  Васильків

In [6]:
print("gereral count rows: %d and columns: %d" % (
    len(users.index),
    len(users.columns)
))

gereral count rows: 5 and columns: 3

In [8]:
users.index

RangeIndex(start=0, stop=5, step=1)

## Завдання 2
У файлі CSV збережено дані про фільми: "Назва", "Жанр", "Рік", "Рейтинг".
 * Прочитайте дані з CSV у DataFrame.
 * Виведіть перші п'ять рядків таблиці.
 * Визначте загальну кількість рядків і стовпців.
 * Визначте типи даних для кожного стовпця.
 * Перевірте наявність пропусків.

In [12]:
movies = pd.read_csv("./notes02_2.csv")
movies.head()

                                          Назва        Жанр     Рік  Рейтинг
0                       F1:Фільм (F1:The Movie)       Спорт  2025.0      7.8
1                    Субстанція (The Substance)        Жахи  2024.0      7.8
2                     Оппенгеймер (Oppenheimer)   Біографія  2023.0      8.4
3  Аватар: Шлях води (Avatar: The Way of Water)  Фантастика  2022.0      7.6
4                                   Дюна (Dune)  Фантастика  2021.0      8.0

In [13]:
print("gereral count rows: %d and columns: %d" % (
    len(movies.index),
    len(movies.columns)
))

gereral count rows: 10 and columns: 4

In [16]:
print("типи даних для кожного стовпця:", movies.dtypes, sep='\n')

типи даних для кожного стовпця:
Назва          str
Жанр           str
Рік        float64
Рейтинг    float64
dtype: object

In [23]:
# Перевірте наявність пропусків.
import numpy as np
print("------- Технічні деталі ---------")
empties = movies.isnull()
print(empties)
positions = np.where(empties)
print(positions)  # (array([6, 9]), array([1, 2]))
print(*zip(*positions))  # (np.int64(6), np.int64(1)) (np.int64(9), np.int64(2))
print("------- Підсумки ---------")
print("Пропуски знаходяться за індексами: ", 
      ", ".join(f"({x};{y})" for (x, y) in zip(*positions))
)

------- Технічні деталі ---------
   Назва   Жанр    Рік  Рейтинг
0  False  False  False    False
1  False  False  False    False
2  False  False  False    False
3  False  False  False    False
4  False  False  False    False
5  False  False  False    False
6  False   True  False    False
7  False  False  False    False
8  False  False  False    False
9  False  False   True    False
(array([6, 9]), array([1, 2]))
(np.int64(6), np.int64(1)) (np.int64(9), np.int64(2))
------- Підсумки ---------
Пропуски знаходяться за індексами:  (6;1), (9;2)

## Завдання 3
Є таблиця співробітників із колонками: "Ім'я", "Вік", "Відділ", "Зарплата".
 * Створіть DataFrame з не менш ніж п'ятьма рядками.
 * Виведіть усі рядки, де зарплата вища за 50000.
 * Відсортуйте таблицю за віком у порядку зростання.
 * Відсортуйте таблицю за зарплатою в порядку спадання.

In [24]:
workers = pd.DataFrame({
    "Ім'я": ["Аскольд", "Олег", "Ігор", "Ольга", "Святослав"],
    "Вік": [30, 33, 42, 27, 37],
    "Відділ": ["Київ", "Хотин", "Чернігів", "Вишгород", "Васильків"],
    "Зарплата": [20000, 40000, 60000, 80000, 100000]
})

In [25]:
workers[ workers["Зарплата"] > 50000 ]

        Ім'я  Вік     Відділ  Зарплата
2       Ігор   42   Чернігів     60000
3      Ольга   27   Вишгород     80000
4  Святослав   37  Васильків    100000

In [26]:
print("за віком у порядку зростання")
workers.sort_values(by="Вік", ascending=True)

за віком у порядку зростання

        Ім'я  Вік     Відділ  Зарплата
3      Ольга   27   Вишгород     80000
0    Аскольд   30       Київ     20000
1       Олег   33      Хотин     40000
4  Святослав   37  Васильків    100000
2       Ігор   42   Чернігів     60000

In [27]:
print("за зарплатою у порядку спадання")
workers.sort_values(by="Зарплата", ascending=False)

за зарплатою у порядку спадання

        Ім'я  Вік     Відділ  Зарплата
4  Святослав   37  Васильків    100000
3      Ольга   27   Вишгород     80000
2       Ігор   42   Чернігів     60000
1       Олег   33      Хотин     40000
0    Аскольд   30       Київ     20000

## Завдання 4
Доступні дані про продажі з колонками: "Товар", "Категорія", "Ціна", "Кількість".
 * Створіть DataFrame з не менш ніж десятьма рядками.
 * Виведіть вихідний DataFrame.
 * Додайте новий стовпець "Виручка" як добуток ціни та кількості.
 * Виведіть оновлений DataFrame.

In [30]:
products = pd.read_csv("./products02_2.csv")
products[["Категорія", "Товар", "Ціна", "Кількість"]].head(3)

     Категорія             Товар   Ціна  Кількість
0  Електроніка       Ноутбук Pro  45000          5
1    Аксесуари  Мишка бездротова   1200         50
2    Аксесуари    Клавіатура RGB   2500         20

In [31]:
products["Виручка"] = products["Ціна"] * products["Кількість"]

products.head(3)

   ID             Товар    Категорія   Ціна  Кількість  Виручка
0   1       Ноутбук Pro  Електроніка  45000          5   225000
1   2  Мишка бездротова    Аксесуари   1200         50    60000
2   3    Клавіатура RGB    Аксесуари   2500         20    50000

## Завдання 5
Є список студентів із зазначенням: "Ім'я", "Курс", "Оцінка".
 * Створіть DataFrame і заповніть його не менш ніж вісьмома рядками.
 * Виведіть вихідний DataFrame.
 * Обчисліть середню оцінку за кожним курсом.
 * Знайдіть максимальну та мінімальну оцінку за кожним курсом.

In [32]:
students = pd.read_csv('./students02_2.csv')
students.head(3)

               Ім'я                  Курс  Оцінка
0  Олександр Коваль   Математичний аналіз      12
1      Марія Бондар  Дискретна математика      10
2   Андрій Ткаченко  Програмування Python      11

In [34]:
marks = students.groupby('Курс')['Оцінка']
print("Середня оцінка за курсом", marks.mean())

Середня оцінка за курсом Курс
Алгоритми та структури     9.000000
Бази даних                 9.000000
Дискретна математика       9.333333
Математичний аналіз        9.666667
Програмування Python      11.666667
Name: Оцінка, dtype: float64

In [37]:
print("Максимальні оцінки:", marks.max(), sep='\n')
print("\nМінімальні оцінки:", marks.min(), sep='\n')

Максимальні оцінки:
Курс
Алгоритми та структури    10
Бази даних                10
Дискретна математика      11
Математичний аналіз       12
Програмування Python      12
Name: Оцінка, dtype: int64

Мінімальні оцінки:
Курс
Алгоритми та структури     8
Бази даних                 8
Дискретна математика       7
Математичний аналіз        6
Програмування Python      11
Name: Оцінка, dtype: int64

## Завдання 6
Зібрано дані про товари та продажі у двох таблицях. Перша містить: "ID", "Назва", "Ціна". Друга містить: "ID", "Кількість".
 * Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками.
 * Виведіть обидва DataFrame.
 * Об'єднайте їх за колонкою "ID".
 * Додайте новий стовпець "Сума" як добуток ціни та кількості.
 * Виведіть підсумковий DataFrame.

In [38]:
sales = pd.read_csv("./sales02_2.csv")
print(products.head(3))
print(sales.head(3))

   ID             Товар    Категорія   Ціна  Кількість  Виручка
0   1       Ноутбук Pro  Електроніка  45000          5   225000
1   2  Мишка бездротова    Аксесуари   1200         50    60000
2   3    Клавіатура RGB    Аксесуари   2500         20    50000
   ID  Продано
0   1        3
1   2        7
2   3        9

In [39]:
results = pd.merge(products, sales, on='ID', how='inner')
results.head()

   ID             Товар    Категорія   Ціна  Кількість  Виручка  Продано
0   1       Ноутбук Pro  Електроніка  45000          5   225000        3
1   2  Мишка бездротова    Аксесуари   1200         50    60000        7
2   3    Клавіатура RGB    Аксесуари   2500         20    50000        9
3   4       Монітор 27"    Периферія  12000         10   120000        8
4   5        Смартфон X      Гаджети  28000         15   420000        4

In [40]:
results['Сума'] = results['Ціна'] * results['Продано']
results

,ID,Товар,Категорія,Ціна,Кількість,Виручка,Продано,Сума
0,1,Ноутбук Pro,Електроніка,45000,5,225000,3,135000
1,2,Мишка бездротова,Аксесуари,1200,50,60000,7,8400
2,3,Клавіатура RGB,Аксесуари,2500,20,50000,9,22500
3,4,"Монітор 27""",Периферія,12000,10,120000,8,96000
4,5,Смартфон X,Гаджети,28000,15,420000,4,112000
5,6,Навушники ANC,Аудіо,5500,30,165000,9,49500
6,7,Принтер лазерний,Офісна техніка,8000,4,32000,3,24000
7,8,Зовнішній HDD,Накопичувачі,3200,25,80000,0,0
8,9,Веб-камера 4K,Периферія,4100,12,49200,5,20500
9,10,Графічний планшет,Гаджети,15000,7,105000,3,45000
10,11,Колонки 2.1,Аудіо,3800,18,68400,10,38000