# Pandas

## Завдання 1
У вас є дані про книги з полями: "Назва", "Автор", "Рік видання", "Ціна".
 * Створіть DataFrame з не менш ніж шістьма рядками.
 * Виведіть увесь DataFrame.
 * Визначте середню ціну книг.
 * Знайдіть книги, видані після 2015 року.
 * Відсортуйте DataFrame за ціною в порядку зростання.

In [1]:
import pandas as pd

In [2]:
dict_books = {
    "Назва": [
        "Тіні забутих предків", 
        "1984", 
        "Відьмак: Останнє бажання", 
        "Маленький принц", 
        "Інтернат"
    ],
    "Автор": [
        "Михайло Коцюбинський", 
        "Джордж Орвелл", 
        "Анджей Сапковський", 
        "Антуан де Сент-Екзюпері", 
        "Сергій Жадан"
    ],
    "Рік видання": [1911, 1949, 1993, 1943, 2017],
    "Ціна": [150.50, 280.00, 320.00, 120.00, 350.00],
}
df = pd.DataFrame(dict_books)

In [3]:
df

                      Назва                    Автор  Рік видання   Ціна
0      Тіні забутих предків     Михайло Коцюбинський         1911  150.5
1                      1984            Джордж Орвелл         1949  280.0
2  Відьмак: Останнє бажання       Анджей Сапковський         1993  320.0
3           Маленький принц  Антуан де Сент-Екзюпері         1943  120.0
4                  Інтернат             Сергій Жадан         2017  350.0

In [4]:
print("Середня ціна книг: ", df["Ціна"].mean())

Середня ціна книг:  244.1

In [5]:
recent_books = df[df["Рік видання"] > 2015]
print("Книги, видані після 2015 року", recent_books)

Книги, видані після 2015 року       Назва         Автор  Рік видання   Ціна
4  Інтернат  Сергій Жадан         2017  350.0

In [6]:
sorted_books = df.sort_values(by="Ціна")
print("Книги, відсортовані за ціною в порядку зростання", sorted_books)

Книги, відсортовані за ціною в порядку зростання                       Назва                    Автор  Рік видання   Ціна
3           Маленький принц  Антуан де Сент-Екзюпері         1943  120.0
0      Тіні забутих предків     Михайло Коцюбинський         1911  150.5
1                      1984            Джордж Орвелл         1949  280.0
2  Відьмак: Останнє бажання       Анджей Сапковський         1993  320.0
4                  Інтернат             Сергій Жадан         2017  350.0

## Завдання 2
У CSV-файлі містяться дані про замовлення: "Номер замовлення", "Клієнт", "Дата", "Сума".
 * Прочитайте дані з файлу в DataFrame.
 * Виведіть перші десять рядків.
 * Визначте кількість замовлень кожного клієнта.
 * Знайдіть максимальну та мінімальну суми замовлень.
 * Підрахуйте загальну суму всіх замовлень.

In [7]:
df = pd.read_csv("orders.csv")

In [8]:
print(df.head(10))

   Номер замовлення     Клієнт        Дата     Сума
0               101  Олександр  2024-05-01  1200.50
1               102      Марія  2024-05-01   450.00
2               103  Олександр  2024-05-02   800.00
3               104       Іван  2024-05-02  2100.00
4               105      Марія  2024-05-03   150.25
5               106  Олександр  2024-05-03  3000.00
6               107      Олена  2024-05-04   560.00
7               108       Іван  2024-05-04   120.00
8               109      Марія  2024-05-05   980.00
9               110      Олена  2024-05-05   430.50

In [9]:
print("Кількість замовлень кожного клієнта\n", df["Клієнт"].value_counts())

Кількість замовлень кожного клієнта
 Клієнт
Олександр    4
Марія        3
Іван         2
Олена        2
Ігор         1
Name: count, dtype: int64

In [10]:
print("Мінімальна сума: ", df['Сума'].min())
print("Максимальна сума: ", df['Сума'].max())

Мінімальна сума:  120.0
Максимальна сума:  3000.0

In [11]:
print("Загальна сума всіх замовлень:: ", df['Сума'].sum())

Загальна сума всіх замовлень::  11641.25

## Завдання 3
Є таблиця з даними про продукти харчування: "Продукт", "Категорія", "Калорії", "Білки".
 * Створіть DataFrame з не менш ніж десятьма рядками.
 * Виведіть увесь DataFrame.
 * Знайдіть усі продукти з калорійністю вище 300.
 * Підрахуйте середню кількість білків за категоріями.
 * Відсортуйте DataFrame за калорійністю в порядку убування.

In [12]:
data = {
    "Продукт": [
        "Куряче філе", "Яблуко", "Волоський горіх", "Сир Гауда", 
        "Вівсянка", "Лосось", "Шоколад чорний", "Броколі", 
        "Яловичина", "Мигдаль"
    ],
    "Категорія": [
        "М'ясо", "Фрукти", "Горіхи", "Молочні продукти", 
        "Крупи", "Риба", "Солодощі", "Овочі", 
        "М'ясо", "Горіхи"
    ],
    "Калорії": [110, 52, 654, 356, 342, 208, 540, 34, 250, 579],
    "Білки": [23.1, 0.3, 15.2, 24.9, 12.5, 20.0, 4.8, 2.8, 26.0, 21.2]
}

df = pd.DataFrame(data)

In [13]:
df

           Продукт         Категорія  Калорії  Білки
0      Куряче філе             М'ясо      110   23.1
1           Яблуко            Фрукти       52    0.3
2  Волоський горіх            Горіхи      654   15.2
3        Сир Гауда  Молочні продукти      356   24.9
4         Вівсянка             Крупи      342   12.5
5           Лосось              Риба      208   20.0
6   Шоколад чорний          Солодощі      540    4.8
7          Броколі             Овочі       34    2.8
8        Яловичина             М'ясо      250   26.0
9          Мигдаль            Горіхи      579   21.2

In [15]:
high_cal_products = df[df["Калорії"] > 300]
print("Продукти з калорійністю вище 300\n", high_cal_products)

Продукти з калорійністю вище 300
            Продукт         Категорія  Калорії  Білки
2  Волоський горіх            Горіхи      654   15.2
3        Сир Гауда  Молочні продукти      356   24.9
4         Вівсянка             Крупи      342   12.5
6   Шоколад чорний          Солодощі      540    4.8
9          Мигдаль            Горіхи      579   21.2

In [16]:
avg_proteins = df.groupby("Категорія")["Білки"].mean()
print("Середня кількість білків за категоріями\n", avg_proteins)

Середня кількість білків за категоріями
 Категорія
Горіхи              18.20
Крупи               12.50
М'ясо               24.55
Молочні продукти    24.90
Овочі                2.80
Риба                20.00
Солодощі             4.80
Фрукти               0.30
Name: Білки, dtype: float64

In [17]:
sorted_df = df.sort_values(by="Калорії", ascending=False)
print("Сортування за калорійністю в порядку убування\n", sorted_df)

Сортування за калорійністю в порядку убування
            Продукт         Категорія  Калорії  Білки
2  Волоський горіх            Горіхи      654   15.2
9          Мигдаль            Горіхи      579   21.2
6   Шоколад чорний          Солодощі      540    4.8
3        Сир Гауда  Молочні продукти      356   24.9
4         Вівсянка             Крупи      342   12.5
8        Яловичина             М'ясо      250   26.0
5           Лосось              Риба      208   20.0
0      Куряче філе             М'ясо      110   23.1
1           Яблуко            Фрукти       52    0.3
7          Броколі             Овочі       34    2.8

## Завдання 4
Зібрано дані про співробітників та їхні проекти: "Ім'я", "Проект", "Години".
 * Створіть DataFrame з не менш ніж вісьмома рядками.
 * Виведіть вихідний DataFrame.
 * Підрахуйте загальну кількість годин за кожним співробітником.
 * Підрахуйте загальну кількість годин за кожним проектом.
 * Знайдіть співробітника, який витратив найбільше годин.

In [18]:
data = {
    "Ім'я": [
        "Роман", "Анна", "Роман", "Олексій", 
        "Анна", "Марія", "Олексій", "Роман"
    ],
    "Проект": [
        "Веб-сайт", "Мобільний додаток", "База даних", "Веб-сайт", 
        "Дизайн", "Мобільний додаток", "Аналітика", "Дизайн"
    ],
    "Години": [25, 40, 15, 30, 20, 35, 10, 12]
}

df = pd.DataFrame(data)

In [19]:
df

      Ім'я             Проект  Години
0    Роман           Веб-сайт      25
1     Анна  Мобільний додаток      40
2    Роман         База даних      15
3  Олексій           Веб-сайт      30
4     Анна             Дизайн      20
5    Марія  Мобільний додаток      35
6  Олексій          Аналітика      10
7    Роман             Дизайн      12

In [25]:
hours_per_employee = df.groupby("Ім'я")["Години"].sum()
print("Загальна кількість годин за кожним співробітником\n", hours_per_employee)

Загальна кількість годин за кожним співробітником
 Ім'я
Анна       60
Марія      35
Олексій    40
Роман      52
Name: Години, dtype: int64

In [26]:
hours_per_project = df.groupby("Проект")["Години"].sum()
print("Загальна кількість годин за кожним проектом\n", hours_per_employee)

Загальна кількість годин за кожним проектом
 Ім'я
Анна       60
Марія      35
Олексій    40
Роман      52
Name: Години, dtype: int64

In [27]:
top_employee = hours_per_employee.idxmax()
max_hours = hours_per_employee.max()
print(f"Співробітник, який витратив найбільше годин: {top_employee} ({max_hours} год)")

Співробітник, який витратив найбільше годин: Анна (60 год)

## Завдання 5
У вас є таблиця продажів квитків: "Фільм", "Місто", "Продані квитки".
 * Створіть DataFrame з не менш ніж дванадцятьма рядками.
 * Виведіть увесь DataFrame.
 * Підрахуйте загальну кількість проданих квитків за кожним фільмом.
 * Підрахуйте загальну кількість квитків по кожному місту.
 * Знайдіть фільм із найбільшою кількістю продажів.

In [32]:
data = {
    "Фільм": [
        "Дюна", "Месники", "Дюна", "Оппенгеймер", 
        "Месники", "Інтерстеллар", "Дюна", "Оппенгеймер",
        "Бетмен", "Інтерстеллар", "Бетмен", "Месники"
    ],
    "Місто": [
        "Київ", "Київ", "Одеса", "Львів", 
        "Львів", "Київ", "Харків", "Одеса", 
        "Харків", "Львів", "Київ", "Одеса"
    ],
    "Продані квитки": [450, 600, 320, 280, 410, 500, 210, 390, 150, 330, 200, 520]
}

df = pd.DataFrame(data)

In [33]:
df

           Фільм   Місто  Продані квитки
0           Дюна    Київ             450
1        Месники    Київ             600
2           Дюна   Одеса             320
3    Оппенгеймер   Львів             280
4        Месники   Львів             410
5   Інтерстеллар    Київ             500
6           Дюна  Харків             210
7    Оппенгеймер   Одеса             390
8         Бетмен  Харків             150
9   Інтерстеллар   Львів             330
10        Бетмен    Київ             200
11       Месники   Одеса             520

In [37]:
tickets_per_movie = df.groupby("Фільм")["Продані квитки"].sum()
print("Загальна кількість годин за кожним співробітником \n", tickets_per_movie)

Загальна кількість годин за кожним співробітником
 Фільм
Інтерстеллар     830
Бетмен           350
Дюна             980
Месники         1530
Оппенгеймер      670
Name: Продані квитки, dtype: int64

In [36]:
tickets_per_city = df.groupby("Місто")["Продані квитки"].sum()
print("Загальна кількість квитків по кожному місту\n", tickets_per_movie)

Загальна кількість квитків по кожному місту
 Фільм
Інтерстеллар     830
Бетмен           350
Дюна             980
Месники         1530
Оппенгеймер      670
Name: Продані квитки, dtype: int64

In [38]:
top_movie = tickets_per_movie.idxmax()
max_tickets = tickets_per_movie.max()
print(f"Фільм із найбільшою кількістю продажів: '{top_movie}' ({max_tickets} квитків)")

Фільм із найбільшою кількістю продажів: 'Месники' (1530 квитків)

## Завдання 6
Дано дві таблиці: перша з інформацією про клієнтів ("ID", "Ім'я", "Місто"), друга — з їхніми замовленнями ("ID клієнта", "Замовлення", "Вартість").
 * Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками кожен.
 * Виведіть обидва DataFrame.
 * Об'єднайте їх за ідентифікатором клієнта.
 * Підрахуйте загальну вартість замовлень за кожним клієнтом.
 * Виведіть результат у вигляді нового DataFrame.

In [39]:
clients_data = {
    "ID": [1, 2, 3, 4, 5],
    "Ім'я": ["Олександр", "Марія", "Іван", "Олена", "Дмитро"],
    "Місто": ["Київ", "Одеса", "Львів", "Харків", "Дніпро"]
}
df_clients = pd.DataFrame(clients_data)

In [40]:
orders_data = {
    "ID клієнта": [1, 2, 1, 3, 4, 2, 5, 3],
    "Замовлення": ["Ноутбук", "Мишка", "Монітор", "Клавіатура", "Принтер", "Навушники", "Планшет", "Колонки"],
    "Вартість": [35000, 800, 7500, 1200, 6000, 2500, 12000, 1500]
}
df_orders = pd.DataFrame(orders_data)

In [42]:
print("Таблиця клієнтів\n", df_clients)
print("Таблиця замовлень\n", df_clients)

Таблиця клієнтів
    ID       Ім'я   Місто
0   1  Олександр    Київ
1   2      Марія   Одеса
2   3       Іван   Львів
3   4      Олена  Харків
4   5     Дмитро  Дніпро
Таблиця замовлень
    ID       Ім'я   Місто
0   1  Олександр    Київ
1   2      Марія   Одеса
2   3       Іван   Львів
3   4      Олена  Харків
4   5     Дмитро  Дніпро

In [43]:
df_merged = pd.merge(df_clients, df_orders, left_on="ID", right_on="ID клієнта")
print("Об'єднання за ідентифікатором клієнта\n", df_merged)

Об'єднання за ідентифікатором клієнта
    ID       Ім'я   Місто  ID клієнта  Замовлення  Вартість
0   1  Олександр    Київ           1     Ноутбук     35000
1   1  Олександр    Київ           1     Монітор      7500
2   2      Марія   Одеса           2       Мишка       800
3   2      Марія   Одеса           2   Навушники      2500
4   3       Іван   Львів           3  Клавіатура      1200
5   3       Іван   Львів           3     Колонки      1500
6   4      Олена  Харків           4     Принтер      6000
7   5     Дмитро  Дніпро           5     Планшет     12000

In [44]:
total_per_client = df_merged.groupby(["ID", "Ім'я"])["Вартість"].sum().reset_index()
print("Виведення результату у вигляді нового DataFrame\n", total_per_client)

Виведення результату у вигляді нового DataFrame
    ID       Ім'я  Вартість
0   1  Олександр     42500
1   2      Марія      3300
2   3       Іван      2700
3   4      Олена      6000
4   5     Дмитро     12000